### ISSUE TITLE
bugs about v2.1

### ISSUE THREAD

**Issue by GodBlessYooo** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#41]
thanks for update again
I find some bus below:

1.Lance Anchor Rage not work
![image](https://user-images.githubusercontent.com/109603892/181037928-4e405343-8435-4079-a241-fddd8aa03430.png)

2.Some weapon charge too much level to correct attack
(Hammer 2/HVB 3/Bow 3)
![image](https://user-images.githubusercontent.com/109603892/181038086-295b1985-0d2d-4c33-9779-97d2b65c6634.png)
![image](https://user-images.githubusercontent.com/109603892/181038189-5704ea1f-d361-423c-b07b-7e311c6a3222.png)
![image](https://user-images.githubusercontent.com/109603892/181038226-8a514c69-6262-43ee-8f8a-3b8a8b0eaf41.png)

**Comment by Bimmr** [comment]
Thanks for the bug report - they should all be fixed in the Github version. I will upload it to Nexus in about 2 hours.
- [Fixed max charge level of HBG](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/c67ae63ce8efd346aa1defac5d0a255c3d4738b4)
- [Fixed Lance not knowing what a config is](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/b3d455344308e49193ff1321e881630144bda874)
- [Fixed bows charge level](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/6bbbf6006267d3f5f740ade572255798186c9d19)
- [Fixed Hammer charge level](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/4001e82bdd3da3ef8801b6b06389c3f494acddcb)

**Comment by GodBlessYooo** [comment]
> * [Fixed Lance not knowing what a config is](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/b3d455344308e49193ff1321e881630144bda874)

I install this fixed file, still not working
the error this time
![image](https://user-images.githubusercontent.com/109603892/181132760-02d6932c-ea49-42f1-b260-aca0100a9a02.png)

**Comment by Bimmr** [comment]
You may need to re-download it or if you're using Vortex it may have put the old file back.

Line 20 in Lance.lua won't cause any errors, so you're using an old file still.

**Comment by Bimmr** [comment]
I'll give it a test tomorrow just to be sure though

**Comment by Bimmr** [comment]
Yup, sorry I feel like an idiot. Line 20 was an issue - looks like that line get reverted when I tried to make the previous update.

I'll update the release build in a few minutes.

**Comment by GodBlessYooo** [comment]
> I'll update the release build in a few minutes.

nvm , I very appreciate your everything what to do
